server {
    listen 80;

    # 1. Sirve la página web principal
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # 2. Enruta las peticiones de productos al Catálogo
    location /api/productos {
        proxy_pass http://catalogo-service:8000;
    }

    # 3. Enruta las peticiones de login a Usuarios
    location /api/usuarios {
        proxy_pass http://usuarios-service:8000;
    }

    # 4. Enruta las peticiones de compras a Órdenes
    location /api/ordenes {
        proxy_pass http://ordenes-service:8000;
    }
}