apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordenes-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ordenes
  template:
    metadata:
      labels:
        app: ordenes
    spec:
      containers:
      - name: ordenes
        image: tu-usuario-docker/ordenes:latest
        imagePullPolicy: IfNotPresent
        ports:
            - containerPort: 8000
        env:
            - name: CATALOGO_URL
              value: "http://catalogo-service:8000"
            - name: DATABASE_URL
              value: "postgresql://admin:secret@postgres-service:5432/ordenes_db"
---
apiVersion: v1
kind: Service
metadata:
  name: ordenes-service
spec:
  selector:
    app: ordenes
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000