apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: usuarios
  template:
    metadata:
      labels:
        app: usuarios
    spec:
      containers:
      - name: usuarios
        image: tu-usuario-docker/usuarios:latest
        imagePullPolicy: IfNotPresent
        ports:
            - containerPort: 8000
        env:
            - name: DATABASE_URL
              value: "postgresql://admin:secret@postgres-service:5432/usuarios_db"
---
apiVersion: v1
kind: Service
metadata:
  name: usuarios-service
spec:
  selector:
    app: usuarios
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000